name: shop_co
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_rating_bar: ^4.0.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Integral CF
      fonts:
        - asset: fonts/IntegralCF-Bold.otf
          weight: 700
    - family: Satoshi
      fonts:
        - asset: fonts/Satoshi-Bold.otf
          weight: 700
        - asset: fonts/Satoshi-Medium.otf
          weight: 500
        - asset: fonts/Satoshi-Regular.otf
          weight: 400
